### PR TITLE
DigitalOcean API support

### PR DESCRIPTION
**Pull request by adriangonzales**
Work on supporting DigitalOcean's API. https://docs.digitalocean.com/reference/api/api-reference/#tag/Droplets

### CODE REVIEW

**Comment by freekmurze** [comment]
Thank you very much for your enthusiasm for this package, it's really motivating!

My plan is to only supported the providers that Spatie needs. Drivers for other server providers should be put in a repo of your own. This way, we don't have to maintain it. In our upcoming docs, I'll glad recommend and link to the driver that you have created.

Should you need any changes in the this core package to make your driver work let me know, and I'll consider changing this. Probably some details over `ServerProvider` class could change, but nothing too big.

I'm looking forward to seeing your completed driver!

**Comment by adriangonzales** [comment]
That makes sense! Looking forward to the instructions and the initial core version.

**Comment by freekmurze** [comment]
@adriangonzales Here are detailed instructions on how to create your own server provider.
https://spatie.be/docs/laravel-dynamic-servers/v1/advanced-usage/creating-your-own-server-provider

If you have any questions, let me know!

**Comment by sidis405** [comment]
Hi @freekmurze 👋 

I've just published a package that provides the DigitalOcean provider [https://github.com/sidis405/laravel-dynamic-servers-digital-ocean](https://github.com/sidis405/laravel-dynamic-servers-digital-ocean)

Overall it was very straightforward thanks to the clear documentation.

There was one problem, which i know is DO specific but might apply to other providers as well (i know EC2 will have a similar problem as i plan to implement that as well).

The issue being that the IP address of the created server is not immediately available within the payload returned upon server creation.

The `VerifyServerStartedJob` will continue to be released and eventually will fire the "ServerRunning" event.
With a new EventServiceProvider i've hooked onto the package level the re-fetching and updating of the meta (which in the end will in fact contain the IP address).

Would you consider some support for this type of thing? (ie. Actions that can be mapped into and run from DynamicServers without having to lean on external support).
And i mean I'd be happy to PR it in :)

Until then it already works well and in either case thank you for the good work man :)

**Comment by freekmurze** [comment]
@sidis405 Very cool! 

> Would you consider some support for this type of thing?

I'm not entirely sure what you are suggestion here, but I would accept PRs that make it easier to handle providers that don't immediately issue IP-addresses. The package hasn't been released yet, so breaking changes are still allowed.

**Comment by sidis405** [comment]
Thank you for the reply @freekmurze 

The problem is not just the IP address per se but also the fact that other server implementations (or even the UpCloud one) can have a custom UpCloudServer::fromApiPayload implementation but the information does not get persisted finally when `VerifyServerStartedJob` is done.

So the idea would be to persist it one last time once the server is running (assuming it will have all the necessary info one would need returned from the API, Ip Address included).

To do it on a package level would not even need to be a breaking change.
The immediate solution would be a `updateServerMeta` method (naming things is hard :p ) in the provider contract and implementation that then gets invoked as soon as the `VerifyServerStartedJob` ensures that the server is running and right before `ServerRunningEvent` is emitted.

The method can use the `ServerProvider@getServer` method and persist the data in the Server model.
This way all the parsing remains centralised in UpCloudServer::fromApiPayload and one can fetch whatever they want from the API and be certain it will get saved once Running.

For better separation of concerns this could even be a Job that gets dispatched from `VerifyServerStartedJob` and performs the action as described above.
Perhaps this would allow users of the package to dispatch this `UpdateServerMetaJob` at will if they need-

If this sounds reasonable i can prep a PR and we can discuss it there to see if it seems like a good idea.

Ps. What i was suggesting in the initial comment was some pre-wired system that allowed users to wire some predefined package listeners (or their own) to package events (like ServerRunningEvent). But then i matured the thought a bit: getting the latest of the Server payload from the remote API seems pretty core and perhaps better handled like i described above. Then users can use the framework's Event/Listener system to get other things done when package events are emitted

**Comment by freekmurze** [comment]
Thanks for explaining. I think I want to leave things as they are for now. The current `ServerProvider` and the way the jobs are set up, give a lot of freedom on how to implement things. `ServerProvider`, can now fetch data and save stuff whenever they want. Sure, that could get messy if you don't structure things well, but I like that the abstract `ServerProvider` now doesn't have any opinion on when, how or if things should be saved.

**Comment by freekmurze** [comment]
@sidis405 I'll add your package do our docs 👍

**Comment by sidis405** [comment]
That makes a lot of sense.
Thank you for considering it 😊

**Pull request closed without merging**
